env = Environment()

env['APP_TARGET'] = 'HeartRateApp'
env['APP_SOURCES'] = ['HeartRateApp.cpp', 'HeartBloom.cpp', 'HeartShape.cpp',
		'KawaseHBloom.cpp']
env['RESOURCES'] = []
env['ASSETS'] = ['model/heart.obj', 'shaders/HeartVert.glsl', 'shaders/HeartFrag.glsl',
		'model/test.png', 'shaders/DisplaceVert.glsl', 'shaders/DisplaceFrag.glsl',
		'shaders/NormalVert.glsl', 'shaders/NormalFrag.glsl',
		'capture/*.xml']
env['DEBUG'] = 0

env = SConscript('../../../blocks/Cinder-PulseSensor/scons/SConscript', exports = 'env')
#env = SConscript('../../../blocks/MndlKit/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
