env = Environment()

env['APP_TARGET'] = 'HeartRateApp'
env['APP_SOURCES'] = ['HeartRateApp.cpp', 'HeartShape.cpp', 'PParams.cpp']
env['RESOURCES'] = []
env['ASSETS'] = ['heart.obj', 'HeartVert.glsl', 'HeartFrag.glsl', 'test.png',
		'DisplaceVert.glsl', 'DisplaceFrag.glsl',
		'NormalVert.glsl', 'NormalFrag.glsl']
env['DEBUG'] = 1

SConscript('../../../scons/SConscript', exports = 'env')
