env = Environment()

env['APP_TARGET'] = 'HeartRateApp'
env['APP_SOURCES'] = ['HeartRateApp.cpp', 'HeartBloom.cpp', 'HeartShape.cpp',
		'KawaseHBloom.cpp']
env['RESOURCES'] = []
env['ASSETS'] = ['model/heart5.obj', 'model/heart.png',
		'shaders/PhongDirectional.frag', 'shaders/PhongDirectional.vert',
		'capture/*.xml']
env['DEBUG'] = 0

env = SConscript('../../../blocks/Cinder-PulseSensor/scons/SConscript', exports = 'env')
#env = SConscript('../../../blocks/MndlKit/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
